# for details see https://github.com/gobuffalo/pop#connecting-to-databases

development:
  dialect: "mysql"
  database: "development"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"

test:
  dialect: "mysql"
  database: "test"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"

production:
  dialect: "mysql"
  database: "production"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
