development:
  dialect: "sqlite3"
  database: C:\Users\samyo\go\src\github.com\TiiQu-Network\claim-verifier-prototype\cache\development.sqlite

test:
  dialect: "sqlite3"
  database: C:\Users\samyo\go\src\github.com\TiiQu-Network\claim-verifier-prototype\cache\test.sqlite

production:
  dialect: "sqlite3"
  database: C:\Users\samyo\go\src\github.com\TiiQu-Network\claim-verifier-prototype\cache\production.sqlite