package actions

import (
	"github.com/TiiQu-Network/claim-verifier-prototype/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Address)
// DB Table: Plural (addresses)
// Resource: Plural (Addresses)
// Path: Plural (/addresses)
// View Template Folder: Plural (/templates/addresses/)

// AddressesResource is the resource for the Address model
type AddressesResource struct {
	buffalo.Resource
}

// List gets all Addresses. This function is mapped to the path
// GET /addresses
func (v AddressesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	addresses := &models.Addresses{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Addresses from the DB
	if err := q.All(addresses); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, addresses))
}

// Show gets the data for one Address. This function is mapped to
// the path GET /addresses/{address_id}
func (v AddressesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Address
	address := &models.Address{}

	// To find the Address the parameter address_id is used.
	if err := tx.Find(address, c.Param("address_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, address))
}

// New renders the form for creating a new Address.
// This function is mapped to the path GET /addresses/new
func (v AddressesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Address{}))
}

// Create adds a Address to the DB. This function is mapped to the
// path POST /addresses
func (v AddressesResource) Create(c buffalo.Context) error {
	// Allocate an empty Address
	address := &models.Address{}

	// Bind address to the html form elements
	if err := c.Bind(address); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(address)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, address))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Address was created successfully")

	// and redirect to the addresses index page
	return c.Render(201, r.Auto(c, address))
}

// Edit renders a edit form for a Address. This function is
// mapped to the path GET /addresses/{address_id}/edit
func (v AddressesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Address
	address := &models.Address{}

	if err := tx.Find(address, c.Param("address_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, address))
}

// Update changes a Address in the DB. This function is mapped to
// the path PUT /addresses/{address_id}
func (v AddressesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Address
	address := &models.Address{}

	if err := tx.Find(address, c.Param("address_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Address to the html form elements
	if err := c.Bind(address); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(address)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, address))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Address was updated successfully")

	// and redirect to the addresses index page
	return c.Render(200, r.Auto(c, address))
}

// Destroy deletes a Address from the DB. This function is mapped
// to the path DELETE /addresses/{address_id}
func (v AddressesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Address
	address := &models.Address{}

	// To find the Address the parameter address_id is used.
	if err := tx.Find(address, c.Param("address_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(address); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Address was destroyed successfully")

	// Redirect to the addresses index page
	return c.Render(200, r.Auto(c, address))
}
